spletna_aplikacija/spletna_aplikacija/Models/MiljarderModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spletna_aplikacija.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class miljarderjiEntities : DbContext
    {
        public miljarderjiEntities()
            : base("name=miljarderjiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<miljarder> miljarder { get; set; }
    }
}

spletna_aplikacija/spletna_aplikacija/Models/MiljarderModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Zan\Documents\Informatika\RPA2020\spletna_aplikacija\spletna_aplikacija\Models\MiljarderModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

spletna_aplikacija/spletna_aplikacija/Models/MiljarderModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

spletna_aplikacija/spletna_aplikacija/Models/miljarder.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spletna_aplikacija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class miljarder
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Priimek { get; set; }
        public Nullable<int> premozenje { get; set; }
        public string podjetje { get; set; }
    }
}

spletna_aplikacija/spletna_aplikacija/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace spletna_aplikacija.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

spletna_aplikacija/spletna_aplikacija/Controllers/miljardersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using spletna_aplikacija.Models;
using System.Xml;

namespace spletna_aplikacija.Controllers
{
    public class miljardersController : Controller
    {
        private miljarderjiEntities db = new miljarderjiEntities();

        // GET: miljarders
        public ActionResult Index()
        {
            return View(db.miljarder.ToList());
        }

        public ActionResult toJson()
        {
            string x;

            return View(db.miljarder.ToList());

        }

        // GET: miljarders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            miljarder miljarder = db.miljarder.Find(id);
            if (miljarder == null)
            {
                return HttpNotFound();
            }
            return View(miljarder);
        }

        // GET: miljarders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: miljarders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ime,Priimek,premozenje,podjetje")] miljarder miljarder)
        {
            if (ModelState.IsValid)
            {
                db.miljarder.Add(miljarder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(miljarder);
        }

        // GET: miljarders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            miljarder miljarder = db.miljarder.Find(id);
            if (miljarder == null)
            {
                return HttpNotFound();
            }
            return View(miljarder);
        }

        // POST: miljarders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ime,Priimek,premozenje,podjetje")] miljarder miljarder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(miljarder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(miljarder);
        }

        // GET: miljarders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            miljarder miljarder = db.miljarder.Find(id);
            if (miljarder == null)
            {
                return HttpNotFound();
            }
            return View(miljarder);
        }

        // POST: miljarders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            miljarder miljarder = db.miljarder.Find(id);
            db.miljarder.Remove(miljarder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

spletna_aplikacija/spletna_aplikacija/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Spletna aplikacija</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Spletna aplikacija", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("nekaj več", "About", "Home")</li>
                    <li>@Html.ActionLink("Miljarderji", "Index", "miljarders")</li>
                    <li>
                    <a href="/ServiceJson.asmx?op=GetMiljardersJSON">JSON</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

spletna_aplikacija/spletna_aplikacija/Views/miljarders/Create.cshtml
@model spletna_aplikacija.Models.miljarder

@{
    ViewBag.Title = "Ustvari";
}

    <h2></h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>miljarder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priimek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priimek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priimek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.premozenje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.premozenje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.premozenje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.podjetje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.podjetje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.podjetje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ustvari" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazaj", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

spletna_aplikacija/spletna_aplikacija/Views/miljarders/Delete.cshtml
@model spletna_aplikacija.Models.miljarder

@{
    ViewBag.Title = "Izbriši";
}
    <h2></h2>
<h3>Potrdi brisanje!</h3>
<div>
    <h4>miljarder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priimek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priimek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.premozenje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.premozenje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.podjetje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.podjetje)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-default" /> |
            @Html.ActionLink("Nazaj", "Index")
        </div>
    }
</div>

spletna_aplikacija/spletna_aplikacija/Views/miljarders/Details.cshtml
@model spletna_aplikacija.Models.miljarder

@{
    ViewBag.Title = "Podrobnosti";
}
    <h2></h2>

<div>
    <h4>miljarder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priimek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priimek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.premozenje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.premozenje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.podjetje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.podjetje)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Spremeni", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Nazaj", "Index")
</p>

spletna_aplikacija/spletna_aplikacija/Views/miljarders/Edit.cshtml
@model spletna_aplikacija.Models.miljarder

@{
    ViewBag.Title = "spremeni";
}
    <h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>miljarder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priimek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priimek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priimek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.premozenje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.premozenje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.premozenje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.podjetje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.podjetje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.podjetje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazaj", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

spletna_aplikacija/spletna_aplikacija/Views/miljarders/Index.cshtml
@model IEnumerable<spletna_aplikacija.Models.miljarder>

@{
    ViewBag.Title = "Index";
}
<h2></h2>
<p>
    @Html.ActionLink("Ustvari", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priimek)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.premozenje)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.podjetje)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priimek)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.premozenje)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.podjetje)
        </td>
        <td>
            @Html.ActionLink("Spremeni", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Podrobnosti", "Details", new { id=item.Id }) |
            @Html.ActionLink("Izbriši", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

spletna_aplikacija/spletna_aplikacija/Views/miljarders/toJson.cshtml
@model IEnumerable<spletna_aplikacija.Models.miljarder>

@{
    ViewBag.Title = "Index";
}
<h2></h2>
<p>
    @Html.ActionLink("Ustvari", "Create")
</p>
<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => (item.Ime))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priimek)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.premozenje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.podjetje)
            </td>
        </tr>
    }

</table>